/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sharedmath_CONSTANTS_H
#define sharedmath_CONSTANTS_H

#include "sharedmath_types.h"

namespace sharedmath {

class sharedmathConstants {
 public:
  sharedmathConstants();

};

extern const sharedmathConstants g_sharedmath_constants;

} // namespace

#endif
