/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tutorialmath_constants.h"

namespace tutorialmath {

const tutorialmathConstants g_tutorialmath_constants;

tutorialmathConstants::tutorialmathConstants() {
  INT32CONSTANT = 9853;

  MAPCONSTANT.insert(std::make_pair("goodnight", "moon"));
  MAPCONSTANT.insert(std::make_pair("hello", "world"));

}

} // namespace

