/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tutorialmath_CONSTANTS_H
#define tutorialmath_CONSTANTS_H

#include "tutorialmath_types.h"

namespace tutorialmath {

class tutorialmathConstants {
 public:
  tutorialmathConstants();

  int32_t INT32CONSTANT;
  std::map<std::string, std::string>  MAPCONSTANT;
};

extern const tutorialmathConstants g_tutorialmath_constants;

} // namespace

#endif
